### ISSUE TITLE
Segmentation Fault on debain 11

### ISSUE THREAD

**Issue by 10maurycy10** [b4ckslash0/deserter#1]
Reproduction:
1. install all required tools
```
    sudo apt install cmake
```
2. follow build instructions
```
    cd scripts/
    chmod +x install.sh
    ./install.sh
```
3. run
```
    sudo ./deserter -t 169.1.1.35 -b 93.184.216.34 -i wlp3s0
```
4. observe segfault

**Comment by 10maurycy10** [comment]
![image](https://user-images.githubusercontent.com/45378255/134563049-251f2998-75a3-49d0-95f3-c1c172a63dcc.png)

**Comment by cr0mll** [comment]
Thank you. It's a known issue, which I am working on fixing. I suspect it has to do with the fact that the tool lacks proper packet filtering at the moment (the library was giving errors, so I had to find a workaround). Right now, your only option is unfortunately to run deserter a few times until it works.

**Comment by cr0mll** [comment]
@10maurycy10 oddly enough, making the packet capturing asynchronous seems to have resolved the issue for me. Can you pull the latest commit and try again? Tell me what results you get :)

**Comment by cr0mll** [comment]
Fixed the segmentation fault which was caused by parsing non-dns packets. The program was dereferencing `nullptr`s for the DNS layer if the packet wasn't a DNS one which caused it to crash.
