### ISSUE TITLE
Segmentation fault, attack seems succesful,

### ISSUE THREAD

**Issue by 10maurycy10** [b4ckslash0/deserter#2]
```
mz@kitty:~/work/deserter$ sudo ./build/deserter -t 192.168.1.57 -b 127.0.0.1 -i wlp3s0
    ____                      __           
   / __ \___  ________  _____/ /____  _____
  / / / / _ \/ ___/ _ \/ ___/ __/ _ \/ ___/
 / /_/ /  __(__  )  __/ /  / /_/  __/ /    
/_____/\___/____/\___/_/   \__/\___/_/     
                                           
Waiting for DNS packets to come...
Poisoning successful.
[ERROR: /home/mz/work/deserter/external/PcapPlusPlus/Packet++/src/DnsResource.cpp: setData:352] DNS record is of type AAAA but given data isn't of type IPv6DnsResourceData
[ERROR: /home/mz/work/deserter/external/PcapPlusPlus/Packet++/src/DnsLayer.cpp: addResource:495] Couldn't set new resource data
Segmentation fault
```

OS: Debian GNU/Linux 11 (bullseye) x86_64
CPU: Intel i5-8350U (8) @ 400MHz

note: target is my local IP

**Comment by cr0mll** [comment]
The only supported record type right now is A. Support is coming for other types, too. Anyway, thank you for submitting the issue - support will be implemented soon enough. The attack probably seems successful because the host is later resolved through IPv4 rather than IPv6.

**Comment by 10maurycy10** [comment]
ok, 
here is a back trace:
![image](https://user-images.githubusercontent.com/45378255/134720109-698b9080-3aee-4c6e-adb0-fd46c83ad90c.png)

**Comment by cr0mll** [comment]
Temporary fix is now available.

**Comment by cr0mll** [comment]
AAAA records are now supported!
